import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";

const manrope = Manrope({ subsets: ["latin"], weight : 'variable' });

export const metadata: Metadata = {
  title: "Interface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className + " flex overflow-hidden top-0 w-screen h-screen"}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}